### ISSUE TITLE
Lecture2-6 contains the wrong files

### ISSUE THREAD

**Issue by paulbhartzog** [bodrovis/EduonixElixirBasics#1]
branch https://github.com/bodrovis/EduonixElixirBasics/tree/lecture2-6 should contain `lambda.exs` as per the video at https://www.udemy.com/course/functional-programming-using-elixir-the-complete-course/learn/lecture/11386360#overview

thx for the great course :-)

**Comment by bodrovis** [comment]
Oh, sorry for that :( I'll fix it. And I really glad you loved the course - it was released some time ago but it's still actual.
